version: "3.9"

services:
  app:
    build: .
    image: ghcr.io/waltermayor/docker-horizon-reduction:latest
    volumes:
      - ./shared:/workspace   # Carpeta compartida host <-> contenedor
    stdin_open: true
    tty: true
    # device_requests:     # Habilitar acceso a GPU: esto no es necesario para .sif
    #   - driver: nvidia   
    #     count: all
    #     capabilities: [gpu]
    # Singularity no empaqueta el driver ni la GPU
    # En cambio, monta automáticamente los drivers de NVIDIA y expone las GPU
