name: Build, Test and Package Docker Image as SIF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (Docker)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image with Docker Compose
        run: |
          docker compose build

      - name: Run tests inside container
        run: |
          docker compose run --rm app bash test.sh

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/docker-horizon-reduction:latest